CREATE TABLE covid_death
(county_id INTEGER NOT NULL PRIMARY KEY REFERENCES county(id),
 total INTEGER NOT NULL REFERENCES covid(deaths),
 white INTEGER NOT NULL,
 black INTEGER NOT NULL,
 AAPI INTEGER NOT NULL,
 native INTEGER NOT NULL,
 other INTEGER NOT NULL,
);
